AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template demonstrates the usage of a high and low priority batch job
  queues. It uses simple EC2 and Spot style Compute Environments. It was created
  based on a sample. 
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 187a3690-c888-442e-894a-a9dbadd3e456
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4b3e712b-216a-4cba-82ec-16418e66e7b5
  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1f749801-c1bc-4a0e-b503-d7c1081cea5a
  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 262a8dbc-2867-4fb1-89d2-c8d7d77b115d
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for the EC2 instances launched into the VPC by Batch
      VpcId: !Ref VPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5567192a-10d5-40fb-aca5-4791e275ee08
  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: 'True'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 62d22b05-1ecf-4a39-9b94-2441aad6bfc1
  Route:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4b7e3c1f-08fa-471f-8d63-a25c07587400
  SubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2152b5be-fdf8-4a24-ba7f-126de15194d7
  BatchServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c31a481b-9ae9-48a5-a796-e47c034679cd
  IamInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref EcsInstanceRole
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2c5b0a60-6cb5-49fa-a3f2-3b4408b96cf9
  EcsInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - >-
          arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c70acd11-4e9a-4b1d-b92c-7aa127b30b70
  SpotIamFleetRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: spotfleet.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetRole'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ae21ab6c-2cdd-4e61-bc7a-fe59a100d07c
  ProdApplicationJob:
    Type: 'AWS::Batch::JobDefinition'
    Properties:
      Type: container
      ContainerProperties:
        Image: !Join 
          - ''
          - - 137112412989.dkr.ecr.
            - !Ref 'AWS::Region'
            - '.amazonaws.com/amazonlinux:latest'
        Vcpus: 2
        Memory: 2000
        Command:
          - echo
          - 'Hello World, I am a high priority job'
      RetryStrategy:
        Attempts: 1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 023a65e4-4ec6-41d1-a3db-9285aa68630e
  TestApplicationJob:
    Type: 'AWS::Batch::JobDefinition'
    Properties:
      Type: container
      ContainerProperties:
        Image: !Join 
          - ''
          - - 137112412989.dkr.ecr.
            - !Ref 'AWS::Region'
            - '.amazonaws.com/amazonlinux:latest'
        Vcpus: 2
        Memory: 2000
        Command:
          - echo
          - 'Hello World, I am a low priority job'
      RetryStrategy:
        Attempts: 1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b373ae24-8502-4b84-998f-ee089602d8a2
  CPUInference:
    Type: 'AWS::Batch::JobDefinition'
    Properties:
      Type: container
      ContainerProperties:
        Image: 'jingpengw/chunkflow.jl:cpu-inference'
        Vcpus: 6
        Memory: 12000
        Command:
          - echo
          - 'Hello World, I am a cpu inference job'
      RetryStrategy:
        Attempts: 2
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9dc8799a-c0b0-4248-a99e-b66556cfb2ce
  HighPriorityJobQueue:
    Type: 'AWS::Batch::JobQueue'
    Properties:
      Priority: 1
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref OnDemandComputeEnvironment
        - Order: 2
          ComputeEnvironment: !Ref SpotComputeEnvironment
    Metadata:
      'AWS::CloudFormation::Designer':
        id: dea37c6b-12ae-48bb-bf28-a5ca4576cd5e
  LowPriorityJobQueue:
    Type: 'AWS::Batch::JobQueue'
    Properties:
      JobQueueName: LowPriorityBatchCloudformationJobqueue
      Priority: 2
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref SpotComputeEnvironment
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 05079ced-462b-438c-84b9-7a0f293c285a
  OnDemandComputeEnvironment:
    Type: 'AWS::Batch::ComputeEnvironment'
    Properties:
      Type: MANAGED
      ComputeResources:
        Type: EC2
        MinvCpus: 0
        DesiredvCpus: 0
        MaxvCpus: 64
        InstanceTypes:
          - optimal
        Subnets:
          - !Ref Subnet
        SecurityGroupIds:
          - !Ref SecurityGroup
        InstanceRole: !Ref IamInstanceProfile
      ServiceRole: !Ref BatchServiceRole
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f1794f80-8bd4-4716-b49c-72101fc11e24
  SpotComputeEnvironment:
    Type: 'AWS::Batch::ComputeEnvironment'
    Properties:
      Type: MANAGED
      ComputeResources:
        Type: SPOT
        MinvCpus: 0
        DesiredvCpus: 0
        MaxvCpus: 64
        InstanceTypes:
          - optimal
        Subnets:
          - !Ref Subnet
        SecurityGroupIds:
          - !Ref SecurityGroup
        InstanceRole: !Ref IamInstanceProfile
        BidPercentage: 40
        SpotIamFleetRole: !Ref SpotIamFleetRole
      ServiceRole: !Ref BatchServiceRole
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 585440b1-6f71-4db3-89b8-1cd965bbe08d
Outputs:
  ProdApplicationJobArn:
    Value: !Ref ProdApplicationJob
  TestApplicationJobArn:
    Value: !Ref TestApplicationJob
  HighPriorityJobQueueArn:
    Value: !Ref HighPriorityJobQueue
  LowPriorityJobQueueArn:
    Value: !Ref LowPriorityJobQueue
  OnDemandComputeEnvironmentArn:
    Value: !Ref OnDemandComputeEnvironment
  SpotComputeEnvironmentArn:
    Value: !Ref SpotComputeEnvironment
Metadata:
  'AWS::CloudFormation::Designer':
    b373ae24-8502-4b84-998f-ee089602d8a2:
      size:
        width: 60
        height: 60
      position:
        x: 210
        'y': 540
      z: 1
      embeds: []
    023a65e4-4ec6-41d1-a3db-9285aa68630e:
      size:
        width: 60
        height: 60
      position:
        x: 320
        'y': 540
      z: 1
      embeds: []
    ae21ab6c-2cdd-4e61-bc7a-fe59a100d07c:
      size:
        width: 60
        height: 60
      position:
        x: 830
        'y': 140
      z: 1
      embeds: []
    c70acd11-4e9a-4b1d-b92c-7aa127b30b70:
      size:
        width: 60
        height: 60
      position:
        x: 460
        'y': 540
      z: 1
      embeds: []
    2c5b0a60-6cb5-49fa-a3f2-3b4408b96cf9:
      size:
        width: 60
        height: 60
      position:
        x: 650
        'y': 540
      z: 1
      embeds: []
      isassociatedwith:
        - c70acd11-4e9a-4b1d-b92c-7aa127b30b70
    c31a481b-9ae9-48a5-a796-e47c034679cd:
      size:
        width: 60
        height: 60
      position:
        x: 800
        'y': 540
      z: 1
      embeds: []
    4b3e712b-216a-4cba-82ec-16418e66e7b5:
      size:
        width: 60
        height: 60
      position:
        x: 720
        'y': 90
      z: 1
      embeds: []
    187a3690-c888-442e-894a-a9dbadd3e456:
      size:
        width: 590
        height: 350
      position:
        x: 60
        'y': 90
      z: 1
      embeds:
        - 62d22b05-1ecf-4a39-9b94-2441aad6bfc1
        - 5567192a-10d5-40fb-aca5-4791e275ee08
        - 1f749801-c1bc-4a0e-b503-d7c1081cea5a
    62d22b05-1ecf-4a39-9b94-2441aad6bfc1:
      size:
        width: 150
        height: 150
      position:
        x: 390
        'y': 150
      z: 2
      parent: 187a3690-c888-442e-894a-a9dbadd3e456
      embeds: []
    5567192a-10d5-40fb-aca5-4791e275ee08:
      size:
        width: 60
        height: 60
      position:
        x: 390
        'y': 360
      z: 2
      parent: 187a3690-c888-442e-894a-a9dbadd3e456
      embeds: []
    585440b1-6f71-4db3-89b8-1cd965bbe08d:
      size:
        width: 60
        height: 60
      position:
        x: 780
        'y': 260
      z: 1
      embeds: []
      isrelatedto:
        - 62d22b05-1ecf-4a39-9b94-2441aad6bfc1
        - 5567192a-10d5-40fb-aca5-4791e275ee08
        - 2c5b0a60-6cb5-49fa-a3f2-3b4408b96cf9
        - ae21ab6c-2cdd-4e61-bc7a-fe59a100d07c
        - c31a481b-9ae9-48a5-a796-e47c034679cd
    05079ced-462b-438c-84b9-7a0f293c285a:
      size:
        width: 60
        height: 60
      position:
        x: 930
        'y': 210
      z: 1
      embeds: []
      isrelatedto:
        - 585440b1-6f71-4db3-89b8-1cd965bbe08d
    f1794f80-8bd4-4716-b49c-72101fc11e24:
      size:
        width: 60
        height: 60
      position:
        x: 780
        'y': 350
      z: 1
      embeds: []
      isrelatedto:
        - 62d22b05-1ecf-4a39-9b94-2441aad6bfc1
        - 5567192a-10d5-40fb-aca5-4791e275ee08
        - 2c5b0a60-6cb5-49fa-a3f2-3b4408b96cf9
        - c31a481b-9ae9-48a5-a796-e47c034679cd
    dea37c6b-12ae-48bb-bf28-a5ca4576cd5e:
      size:
        width: 60
        height: 60
      position:
        x: 930
        'y': 350
      z: 1
      embeds: []
      isrelatedto:
        - f1794f80-8bd4-4716-b49c-72101fc11e24
        - 585440b1-6f71-4db3-89b8-1cd965bbe08d
    262a8dbc-2867-4fb1-89d2-c8d7d77b115d:
      source:
        id: 4b3e712b-216a-4cba-82ec-16418e66e7b5
      target:
        id: 187a3690-c888-442e-894a-a9dbadd3e456
      z: 1
    1f749801-c1bc-4a0e-b503-d7c1081cea5a:
      size:
        width: 240
        height: 240
      position:
        x: 90
        'y': 150
      z: 2
      parent: 187a3690-c888-442e-894a-a9dbadd3e456
      embeds:
        - 4b7e3c1f-08fa-471f-8d63-a25c07587400
    2152b5be-fdf8-4a24-ba7f-126de15194d7:
      source:
        id: 1f749801-c1bc-4a0e-b503-d7c1081cea5a
      target:
        id: 62d22b05-1ecf-4a39-9b94-2441aad6bfc1
      z: 2
    4b7e3c1f-08fa-471f-8d63-a25c07587400:
      size:
        width: 60
        height: 60
      position:
        x: 120
        'y': 210
      z: 3
      parent: 1f749801-c1bc-4a0e-b503-d7c1081cea5a
      embeds: []
      references:
        - 4b3e712b-216a-4cba-82ec-16418e66e7b5
    9dc8799a-c0b0-4248-a99e-b66556cfb2ce:
      size:
        width: 60
        height: 60
      position:
        x: 110
        'y': 540
      z: 1
      embeds: []
