qsub -V -b y -cwd ./data/z0-y0-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x4/trainning_spec/run.sh 
