qsub -V -b y -cwd ./data/z0-y0-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x5/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x6/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x7/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x8/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y0-x9/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x5/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x6/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x7/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x8/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y1-x9/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x5/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x6/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x7/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x8/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y2-x9/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x5/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x6/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x7/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x8/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y3-x9/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y4-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y4-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y4-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y4-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y4-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y4-x5/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y4-x6/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y4-x7/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y4-x8/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y4-x9/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y5-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y5-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y5-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y5-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y5-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y5-x5/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y5-x6/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y5-x7/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y5-x8/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y5-x9/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y6-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y6-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y6-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y6-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y6-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y6-x5/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y6-x6/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y6-x7/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y6-x8/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y6-x9/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y7-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y7-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y7-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y7-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y7-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y7-x5/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y7-x6/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y7-x7/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y7-x8/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y7-x9/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y8-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y8-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y8-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y8-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y8-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y8-x5/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y8-x6/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y8-x7/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y8-x8/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y8-x9/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y9-x0/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y9-x1/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y9-x2/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y9-x3/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y9-x4/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y9-x5/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y9-x6/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y9-x7/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y9-x8/trainning_spec/run.sh 
qsub -V -b y -cwd ./data/z0-y9-x9/trainning_spec/run.sh 
